# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d7ade941953115d60035ef73b5e5c7298cb54d42cdcd1ff50229616d3bb9fcd3fb8212c3dcf87783c6109f7bcc63cdffacd408a51b9e90b811b12ddd369dc0

test:
  secret_key_base: 939c71d88df08568d370dc04af7c12d6b187193e7fb91b5eb7bcfdf4c17f8a6afecd8b54f623941b911d9bf36bf411a574f5d15590039ff03341ff4da5148c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
